# Site settings
title: Milan Hybner
email: 1@m23.cz
description: The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.
url: "http://m23.cz" # the base hostname & protocol for your site
phone: 776412328
twitter_username: milanhybner
facebook_username: hybner.milan

# Build settings
markdown: kramdown

collections:
  us:
    output: true
  zb:
    output: true
  tr:
    output: true

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "us"
    values:
      layout: "default"
  -
    scope:
      path: "zb"
    values:
      layout: "default"
  -
    scope:
      path: "tr"
    values:
      layout: "default"
